### ISSUE TITLE
为什么不支持开机自启服务

### ISSUE THREAD

**Issue by fanhua1994** [xiaoqidun/anmpp#10]
每次开机还需要去手机启动服务。

**Comment by xiaoqidun** [comment]
支持的，组件选择选择需要开机启动的服务，然后勾选开机自动启动，关闭电池优化，各种安全软件允许自动启动。

繁华 <notifications@github.com> 于 2018年10月10日周三 11:11写道：

**Comment by fanhua1994** [comment]
好的哦。
