### ISSUE TITLE
导出环境时报错

### ISSUE THREAD

**Issue by fanhua1994** [xiaoqidun/anmpp#11]
今天在使用的时候发现。导出环境报错broken pipe。然后通过FTP将环境包下载改名anmpp.tar.bz2发现其与正常。mysql无法正常启动。请问这个怎么解决呢。

**Comment by xiaoqidun** [comment]
大概是shell环境导致的，你可以查看软件数据目录下的导出环境脚本，找个终端模拟器手动执行命令导出。

繁华 <notifications@github.com>于2018年10月12日周五 下午2:11写道：
