### ISSUE TITLE
默认安装的是php5.6。怎样换成php7.2?

### ISSUE THREAD

**Issue by jellyfish9** [xiaoqidun/anmpp#13]
默认安装的是php5.6。怎样换成php7.2?
php-cgi放在哪？

**Comment by xiaoqidun** [comment]
下载php-fpm.bz2，解压后替换程序中的php-fpm文件，给予0755程序权限。

王伟 <notifications@github.com> 于2019年1月10日周四 下午2:14写道：

**Comment by jellyfish9** [comment]
3ks
