### ISSUE TITLE
资源下载失败+需要授权程序root运行守护进程

### ISSUE THREAD

**Issue by 456vv** [xiaoqidun/anmpp#15]
已经授权root，还是提示“需要授权程序root运行守护进程”。卸载后安装最新版本的，一样提示。

**Comment by xiaoqidun** [comment]
资源可以手动下载，提示没有root运行守护进程那基本上就是没有root或者程序没有访问网络权限没有办法与anmpp daemon通讯。root推荐使用magisk，另外VMOS之类的基于android工作空间的假虚拟化软件的root是不起作用的。
