### ISSUE TITLE
重启手机之后anmpp环境目录就没了

### ISSUE THREAD

**Issue by ghost** [xiaoqidun/anmpp#2]
手机是红米note3高配版，ROM是官方RR 5.8.0 (Android 7.1.1)每夜版，只要重启手机，data/dara中跟anmpp有关的目录都没有了，包括网站文件在内。

**Comment by xiaoqidun** [comment]
android 7.1 +
重启会自动删除/data/data目录下不是软件数据目录的目录（就是没有与软件包名一样的目录）
android.bftpd
android.mysql
android.nginx
android.ngrok
android.pgsql
android.php-fpm
android.wwwroot
都是因为没有对应的软件包而被系统自动删除了，解决这个问题有二种办法
1.自行用android studio等安卓开发软件编译以上包名一样的软件并安装（helloworld就行）
2.需要我来解决，就是更改anmpp环境/data/data这个默认目录，改变这个目录需要重新编译所有组件
方法一是可行的，apk我已经针对android 7 +做了兼容，只要安装几个空包保证目录不被自动删除即可
方法二呢，我目前比较忙，时间比较少，我有时间会考虑更改根目录的，需要有时间才能重新编译所有

**Comment by ghost** [comment]
@xiaoqidun 原来如此，方法一不太好，因为为此还要多装7个并没有实际作用的app，还是用方法二吧，就放内置SD卡上。
