### ISSUE TITLE
English Translation Please

### ISSUE THREAD

**Issue by 0E800** [xiaoqidun/anmpp#3]
May you please help translate to english?

**Comment by 0E800** [comment]
Here is `strings.xml` for English translation. Please note I still have not gotten the application to serve a Nginx site yet.

````
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="abc_action_bar_home_description">Navigate home</string>
    <string name="abc_action_bar_home_description_format">%1$s, %2$s</string>
    <string name="abc_action_bar_home_subtitle_description_format">%1$s, %2$s, %3$s</string>
    <string name="abc_action_bar_up_description">Navigate up</string>
    <string name="abc_action_menu_overflow_description">More options</string>
    <string name="abc_action_mode_done">Done</string>
    <string name="abc_activity_chooser_view_see_all">See all</string>
    <string name="abc_activitychooserview_choose_application">Choose an app</string>
    <string name="abc_capital_off">OFF</string>
    <string name="abc_capital_on">ON</string>
    <string name="abc_search_hint">Search…</string>
    <string name="abc_searchview_description_clear">Clear query</string>
    <string name="abc_searchview_description_query">Search query</string>
    <string name="abc_searchview_description_search">Search</string>
    <string name="abc_searchview_description_submit">Submit query</string>
    <string name="abc_searchview_description_voice">Voice search</string>
    <string name="abc_shareactionprovider_share_with">Share with</string>
    <string name="abc_shareactionprovider_share_with_application">Share with %s</string>
    <string name="abc_toolbar_collapse_description">Collapse</string>
    <string name="search_menu_title">Search</string>
    <string name="status_bar_notification_info_overflow">999+</string>
    <string name="anmpp_aite_me">Actel network</string>
    <string name="anmpp_app_check_update">Check for updates</string>
    <string name="anmpp_app_check_update_dialog">Checking for updates ....</string>
    <string name="anmpp_app_check_update_error">Temporarily unable to check for updates</string>
    <string name="anmpp_app_check_update_latest">You are using the latest version</string>
    <string name="anmpp_app_check_update_no">Update later</string>
    <string name="anmpp_app_check_update_ok">Get updates</string>
    <string name="anmpp_app_check_update_title">Check FOR new version</string>
    <string name="anmpp_app_start_binary_fail">Error initializing environment</string>
    <string name="anmpp_app_start_init">Initializing environment ....</string>
    <string name="anmpp_base_admin">Basic settings</string>
    <string name="anmpp_bftpd_run_status_false">Click here to start the service</string>
    <string name="anmpp_bftpd_run_status_true">We are running ....</string>
    <string name="anmpp_bftpd_run_title">Service Management: BFTPD</string>
    <string name="anmpp_bftpd_set">Open components: BFTPD</string>
    <string name="anmpp_bftpd_set_false">Has closed components: BFTPD</string>
    <string name="anmpp_bftpd_set_true">Has opened components: BFTPD</string>
    <string name="anmpp_binary_version_none">It does not recognize the version you are using</string>
    <string name="anmpp_boot_autostart_ngrokc_done">Perform network penetration is completed</string>
    <string name="anmpp_boot_autostart_ngrokc_set">Start NG automatically within the network through service</string>
    <string name="anmpp_boot_autostart_ngrokc_set_false">NG has to be turned off automatically within the network penetration</string>
    <string name="anmpp_boot_autostart_ngrokc_set_true">NG is turned on automatically within the network penetration</string>
    <string name="anmpp_boot_autostart_set">Set host environment at startup</string>
    <string name="anmpp_boot_autostart_set_false">No autostart boot environment at startup</string>
    <string name="anmpp_boot_autostart_set_true">Yes autostart boot environment at startup</string>
    <string name="anmpp_install_dialog_file_not_found">The installation package file does not exist, Not Found！</string>
    <string name="anmpp_install_dialog_message">We need to continue? We will use the highest authority the implementation of a program to complete the installation super environment！</string>
    <string name="anmpp_install_dialog_message_zip">Select the local installation package path:</string>
    <string name="anmpp_install_dialog_msg">Integrated environment being installed ....</string>
    <string name="anmpp_install_dialog_no">Install later</string>
    <string name="anmpp_install_dialog_ok">Install now</string>
    <string name="anmpp_install_dialog_title">Install an integrated environment from the local file?</string>
    <string name="anmpp_install_done">Super integrated environment has been successfully installed</string>
    <string name="anmpp_mysql_run_status_false">Click here to start the service</string>
    <string name="anmpp_mysql_run_status_true">We are running ....</string>
    <string name="anmpp_mysql_run_title">Service Management: MYSQL</string>
    <string name="anmpp_mysql_set">Open components: MYSQL</string>
    <string name="anmpp_mysql_set_false">Has closed components: MYSQL</string>
    <string name="anmpp_mysql_set_true">Has opened components: MYSQL</string>
    <string name="anmpp_nattun_set">Network penetration NAT</string>
    <string name="anmpp_nginx_run_status_false">Click here to start the service</string>
    <string name="anmpp_nginx_run_status_true">We are running ....</string>
    <string name="anmpp_nginx_run_title">Service Management: NGINX</string>
    <string name="anmpp_nginx_set">Open components: NGINX</string>
    <string name="anmpp_nginx_set_false">Has closed components: NGINX</string>
    <string name="anmpp_nginx_set_true">Has opened components: NGINX</string>
    <string name="anmpp_ngrok_ngrokc_log_load">Log Loading ....</string>
    <string name="anmpp_ngrok_ngrokc_log_msg">Click here to see the penetration log NG</string>
    <string name="anmpp_ngrok_ngrokc_log_none">No log for you to view</string>
    <string name="anmpp_ngrok_ngrokc_log_title">Network penetration log NGROK</string>
    <string name="anmpp_ngrok_option_set_check_fail">Verify penetrate option fails</string>
    <string name="anmpp_ngrok_option_set_clear_done">Clear successful penetration options</string>
    <string name="anmpp_ngrok_option_set_edit_no">Cancel</string>
    <string name="anmpp_ngrok_option_set_edit_ok">Save</string>
    <string name="anmpp_ngrok_option_set_edit_title">Provisioning network through options NG</string>
    <string name="anmpp_ngrok_option_set_none">Click here to set up the network through the related options</string>
    <string name="anmpp_ngrok_option_set_save_done">Save Options successful penetration</string>
    <string name="anmpp_ngrok_option_set_text">Network penetration options NG</string>
    <string name="anmpp_ngrokc_admin">Network penetration Management</string>
    <string name="anmpp_ngrokc_run">We are running ....</string>
    <string name="anmpp_ngrokc_start_dialog_msg">Starting within the network penetration ....</string>
    <string name="anmpp_ngrokc_status_check_dialog_msg">Checking for penetration state ....</string>
    <string name="anmpp_ngrokc_stop">Click here to start the network penetration NG</string>
    <string name="anmpp_ngrokc_stop_dialog_msg">Stopping network penetration ....</string>
    <string name="anmpp_noroot">This does not have permission to run the desired action</string>
    <string name="anmpp_pgsql_run_status_false">Click here to start the service</string>
    <string name="anmpp_pgsql_run_status_true">We are running ....</string>
    <string name="anmpp_pgsql_run_title">Service Management: PGSQL</string>
    <string name="anmpp_pgsql_set">Open components: PGSQL</string>
    <string name="anmpp_pgsql_set_false">Has closed components: PGSQL</string>
    <string name="anmpp_pgsql_set_true">Has opened components: PGSQL</string>
    <string name="anmpp_phpfpm_run_status_false">Click here to start the service</string>
    <string name="anmpp_phpfpm_run_status_true">We are running ....</string>
    <string name="anmpp_phpfpm_run_title">Service Management: PHP-FPM</string>
    <string name="anmpp_phpfpm_set">Open components: PHP-FPM</string>
    <string name="anmpp_phpfpm_set_false">Has closed components: PHP-FPM</string>
    <string name="anmpp_phpfpm_set_true">It has opened components: PHP-FPM</string>
    <string name="anmpp_plug_admin">Component Management</string>
    <string name="anmpp_plug_run_check">Status check ....</string>
    <string name="anmpp_plug_run_init">Starting in ....</string>
    <string name="anmpp_plug_run_stop">Turning off the ....</string>
    <string name="anmpp_reload">Environment restart</string>
    <string name="anmpp_reload_dialog_done">Perform the restart operation is completed</string>
    <string name="anmpp_reload_dialog_message">Restarting all of the components you have open ....</string>
    <string name="anmpp_run_set">Operation Management</string>
    <string name="anmpp_start">Startup environment</string>
    <string name="anmpp_start_dialog_done">The start operation is completed</string>
    <string name="anmpp_start_dialog_message">Starting all the components you have open ....</string>
    <string name="anmpp_stop">Stop Environment</string>
    <string name="anmpp_stop_dialog_done">Stop execution operation is completed</string>
    <string name="anmpp_stop_dialog_message">Turning off all the components you have open ....</string>
    <string name="anmpp_support">Support Center</string>
    <string name="anmpp_uninstall_dialog_message">Super environment will remove all components (including WEB directory), at the end of unloading operations APP will automatically turn off, you need to proceed?</string>
    <string name="anmpp_uninstall_dialog_msg">Integrated environment is unloading ....</string>
    <string name="anmpp_uninstall_dialog_no">Temporarily uninstall</string>
    <string name="anmpp_uninstall_dialog_ok">Completely uninstall</string>
    <string name="anmpp_uninstall_dialog_title">Completely remove the machine is installed in the super environment do?</string>
    <string name="anmpp_uninstall_done">Super integrated environment has been successfully uninstalled</string>
    <string name="anmpp_version_title">Version Information</string>
    <string name="anmpp_wake_lock_set">Always keep the device awake state</string>
    <string name="anmpp_wake_lock_set_false">The closure device remains in the awake state</string>
    <string name="anmpp_wake_lock_set_true">It has been keeping the device awake state</string>
    <string name="anmpp_webthen_net">Technical Communities</string>
    <string name="app_name">Super Host</string>
    <string name="chooser_brw">Please select a browser</string>
    <string name="env_admin">Environmental Management</string>
    <string name="install">Installation Environment</string>
    <string name="install_uninstall">Install uninstall</string>
    <string name="navigation_drawer_close">Close menu</string>
    <string name="navigation_drawer_open">Open the menu</string>
    <string name="open_localhost">Open the local host address has been performed for you</string>
    <string name="title_activity_main">Super Host</string>
    <string name="uninstall">Uninstall environment</string>
    <string name="abc_font_family_body_1_material">sans-serif</string>
    <string name="abc_font_family_body_2_material">sans-serif-medium</string>
    <string name="abc_font_family_button_material">sans-serif-medium</string>
    <string name="abc_font_family_caption_material">sans-serif</string>
    <string name="abc_font_family_display_1_material">sans-serif</string>
    <string name="abc_font_family_display_2_material">sans-serif</string>
    <string name="abc_font_family_display_3_material">sans-serif</string>
    <string name="abc_font_family_display_4_material">sans-serif-light</string>
    <string name="abc_font_family_headline_material">sans-serif</string>
    <string name="abc_font_family_menu_material">sans-serif</string>
    <string name="abc_font_family_subhead_material">sans-serif</string>
    <string name="abc_font_family_title_material">sans-serif-medium</string>
    <string name="appbar_scrolling_view_behavior">android.support.design.widget.AppBarLayout$ScrollingViewBehavior</string>
    <string name="bottom_sheet_behavior">android.support.design.widget.BottomSheetBehavior</string>
    <string name="character_counter_pattern">%1$d / %2$d</string>
</resources>
````

Result:
![Imgur](http://i.imgur.com/2Ppnp9Il.png)

**Comment by xiaoqidun** [comment]
thank you，next compile join。

**Comment by xiaoqidun** [comment]
@0E800 
<resources>
    <string name="app_name">超级主机</string>
    <string name="anmpp_support">支持中心</string>
    <string name="anmpp_aite_me">爱特网络</string>
    <string name="anmpp_app_check_update">检查更新</string>
    <string name="anmpp_app_check_update_dialog">正在检查更新中....</string>
    <string name="anmpp_app_check_update_error">暂时无法检查更新</string>
    <string name="anmpp_app_check_update_latest">您使用的是最新版本</string>
    <string name="anmpp_app_check_update_title">检查到新版本，是否立即获取更新？</string>
    <string name="anmpp_app_check_update_ok">获取更新</string>
    <string name="anmpp_app_check_update_no">稍后更新</string>
    <string name="anmpp_webthen_net">技术社区</string>
    <string name="title_activity_main">超级主机</string>
    <string name="navigation_drawer_open">打开菜单</string>
    <string name="navigation_drawer_close">关闭菜单</string>
    <string name="env_admin">环境管理</string>
    <string name="install">安装环境</string>
    <string name="uninstall">卸载环境</string>
    <string name="install_uninstall">安装卸载</string>
    <string name="anmpp_start">启动环境</string>
    <string name="anmpp_stop">停止环境</string>
    <string name="anmpp_reload">重启环境</string>
    <string name="anmpp_noroot">本程序没有运行所需操作的权限</string>
    <string name="anmpp_app_start_init">正在初始化环境....</string>
    <string name="anmpp_app_start_binary_fail">初始化环境错误</string>
    <string name="anmpp_boot_autostart_set">开机自动启动超级主机环境</string>
    <string name="anmpp_boot_autostart_set_true">已经开启环境开机自动启动</string>
    <string name="anmpp_boot_autostart_set_false">已经关闭环境开机自动启动</string>
    <string name="anmpp_boot_autostart_ngrokc_set">开机自动运行内网穿透服务</string>
    <string name="anmpp_wake_lock_set">始终使设备保持在清醒状态</string>
    <string name="anmpp_wake_lock_set_true">已经使设备保持在清醒状态</string>
    <string name="anmpp_wake_lock_set_false">关闭使设备保持在清醒状态</string>
    <string name="anmpp_boot_autostart_ngrokc_set_true">已经开启开机自动内网穿透</string>
    <string name="anmpp_boot_autostart_ngrokc_set_false">已经关闭开机自动内网穿透</string>
    <string name="anmpp_boot_autostart_ngrokc_done">执行内网穿透完毕</string>
    <string name="anmpp_bftpd_set">开启组件：BFTPD</string>
    <string name="anmpp_bftpd_set_true">已经开启组件：BFTPD</string>
    <string name="anmpp_bftpd_set_false">已经关闭组件：BFTPD</string>
    <string name="anmpp_nginx_set">开启组件：NGINX</string>
    <string name="anmpp_nginx_set_true">已经开启组件：NGINX</string>
    <string name="anmpp_nginx_set_false">已经关闭组件：NGINX</string>
    <string name="anmpp_mysql_set">开启组件：MYSQL</string>
    <string name="anmpp_mysql_set_true">已经开启组件：MYSQL</string>
    <string name="anmpp_mysql_set_false">已经关闭组件：MYSQL</string>
    <string name="anmpp_pgsql_set">开启组件：PGSQL</string>
    <string name="anmpp_pgsql_set_true">已经开启组件：PGSQL</string>
    <string name="anmpp_pgsql_set_false">已经关闭组件：PGSQL</string>
    <string name="anmpp_phpfpm_set">开启组件：PHP-FPM</string>
    <string name="anmpp_phpfpm_set_true">已经开启组件：PHP-FPM</string>
    <string name="anmpp_phpfpm_set_false">已经关闭组件：PHP-FPM</string>
    <string name="anmpp_run_set">运行管理</string>
    <string name="anmpp_plug_run_init">正在启动中....</string>
    <string name="anmpp_plug_run_stop">正在关闭中....</string>
    <string name="anmpp_plug_run_check">状态检查中....</string>
    <string name="anmpp_bftpd_run_title">服务管理：BFTPD</string>
    <string name="anmpp_bftpd_run_status_true">正在运行中....</string>
    <string name="anmpp_bftpd_run_status_false">点击这里启动服务</string>
    <string name="anmpp_nginx_run_title">服务管理：NGINX</string>
    <string name="anmpp_nginx_run_status_true">正在运行中....</string>
    <string name="anmpp_nginx_run_status_false">点击这里启动服务</string>
    <string name="anmpp_mysql_run_title">服务管理：MYSQL</string>
    <string name="anmpp_mysql_run_status_true">正在运行中....</string>
    <string name="anmpp_mysql_run_status_false">点击这里启动服务</string>
    <string name="anmpp_pgsql_run_title">服务管理：PGSQL</string>
    <string name="anmpp_pgsql_run_status_true">正在运行中....</string>
    <string name="anmpp_pgsql_run_status_false">点击这里启动服务</string>
    <string name="anmpp_phpfpm_run_title">服务管理：PHP-FPM</string>
    <string name="anmpp_phpfpm_run_status_true">正在运行中....</string>
    <string name="anmpp_phpfpm_run_status_false">点击这里启动服务</string>
    <string name="anmpp_plug_admin">组件管理</string>
    <string name="anmpp_base_admin">基本设置</string>
    <string name="anmpp_nattun_set">内网穿透</string>
    <string name="anmpp_ngrok_ngrokc_log_msg">点击这里查看穿透日志</string>
    <string name="anmpp_ngrok_ngrokc_log_title">内网穿透日志</string>
    <string name="anmpp_ngrok_ngrokc_log_load">日志加载中....</string>
    <string name="anmpp_ngrok_ngrokc_log_none">暂无日志供你查看</string>
    <string name="anmpp_ngrok_option_set_text">内网穿透选项</string>
    <string name="anmpp_ngrok_option_set_edit_title">设置内网穿透选项</string>
    <string name="anmpp_ngrok_option_set_edit_no">取消</string>
    <string name="anmpp_ngrok_option_set_edit_ok">保存</string>
    <string name="anmpp_ngrok_option_set_none">点此设置内网穿透相关选项</string>
    <string name="anmpp_ngrok_option_set_save_done">保存穿透选项成功</string>
    <string name="anmpp_ngrok_option_set_clear_done">清除穿透选项成功</string>
    <string name="anmpp_ngrok_option_set_check_fail">验证穿透选项失败</string>
    <string name="anmpp_ngrokc_admin">内网穿透管理</string>
    <string name="anmpp_ngrokc_run">正在运行中....</string>
    <string name="anmpp_ngrokc_stop">点此启动内网穿透</string>
    <string name="anmpp_ngrokc_status_check_dialog_msg">正在检查穿透状态....</string>
    <string name="anmpp_ngrokc_start_dialog_msg">正在启动内网穿透....</string>
    <string name="anmpp_ngrokc_stop_dialog_msg">正在停止内网穿透....</string>
    <string name="anmpp_stop_dialog_message">正在关闭你所开启的所有组件....</string>
    <string name="anmpp_start_dialog_message">正在启动你所开启的所有组件....</string>
    <string name="anmpp_reload_dialog_message">正在重启你所开启的所有组件....</string>
    <string name="anmpp_stop_dialog_done">执行停止操作完毕</string>
    <string name="anmpp_start_dialog_done">执行启动操作完毕</string>
    <string name="anmpp_reload_dialog_done">执行重启操作完毕</string>
    <string name="anmpp_install_dialog_title">从本机文件中安装集成环境？</string>
    <string name="anmpp_install_dialog_message">需要继续吗？将会使用系统最高权限执行一段程序来完成超级环境安装（安装结束时APP会自动关闭）！</string>
    <string name="anmpp_install_dialog_message_zip">选取的本地安装包路径：</string>
    <string name="anmpp_install_dialog_ok">确定安装</string>
    <string name="anmpp_install_dialog_no">稍后安装</string>
    <string name="anmpp_install_dialog_file_not_found">本机安装包文件不存在，请先准备好安装包文件！</string>
    <string name="anmpp_install_dialog_msg">集成环境正在安装中....</string>
    <string name="anmpp_install_done">超级集成环境已经成功安装</string>
    <string name="anmpp_uninstall_dialog_title">完全删除安装在本机的超级环境吗？</string>
    <string name="anmpp_uninstall_dialog_message">将会删除超级环境所有组件（包含WEB目录），卸载操作结束时APP会自动关闭，需要继续操作吗？</string>
    <string name="anmpp_uninstall_dialog_ok">彻底卸载</string>
    <string name="anmpp_uninstall_dialog_no">暂不卸载</string>
    <string name="anmpp_uninstall_dialog_msg">集成环境正在卸载中....</string>
    <string name="anmpp_uninstall_done">超级集成环境已经成功卸载</string>
    <string name="chooser_brw">请选择浏览器</string>
    <string name="open_localhost">已经为你执行打开本地主机地址</string>
    <string name="anmpp_version_title">版本信息</string>
    <string name="anmpp_binary_version_none">暂时无法识别你使用的版本</string>
</resources>

**Comment by xiaoqidun** [comment]
`<resources>
    <string name="app_name">超级主机</string>
    <string name="anmpp_support">支持中心</string>
    <string name="anmpp_aite_me">爱特网络</string>
    <string name="anmpp_app_check_update">检查更新</string>
    <string name="anmpp_app_check_update_dialog">正在检查更新中....</string>
    <string name="anmpp_app_check_update_error">暂时无法检查更新</string>
    <string name="anmpp_app_check_update_latest">您使用的是最新版本</string>
    <string name="anmpp_app_check_update_title">检查到新版本，是否立即获取更新？</string>
    <string name="anmpp_app_check_update_ok">获取更新</string>
    <string name="anmpp_app_check_update_no">稍后更新</string>
    <string name="anmpp_webthen_net">技术社区</string>
    <string name="title_activity_main">超级主机</string>
    <string name="navigation_drawer_open">打开菜单</string>
    <string name="navigation_drawer_close">关闭菜单</string>
    <string name="env_admin">环境管理</string>
    <string name="install">安装环境</string>
    <string name="uninstall">卸载环境</string>
    <string name="install_uninstall">安装卸载</string>
    <string name="anmpp_start">启动环境</string>
    <string name="anmpp_stop">停止环境</string>
    <string name="anmpp_reload">重启环境</string>
    <string name="anmpp_noroot">本程序没有运行所需操作的权限</string>
    <string name="anmpp_app_start_init">正在初始化环境....</string>
    <string name="anmpp_app_start_binary_fail">初始化环境错误</string>
    <string name="anmpp_boot_autostart_set">开机自动启动超级主机环境</string>
    <string name="anmpp_boot_autostart_set_true">已经开启环境开机自动启动</string>
    <string name="anmpp_boot_autostart_set_false">已经关闭环境开机自动启动</string>
    <string name="anmpp_boot_autostart_ngrokc_set">开机自动运行内网穿透服务</string>
    <string name="anmpp_wake_lock_set">始终使设备保持在清醒状态</string>
    <string name="anmpp_wake_lock_set_true">已经使设备保持在清醒状态</string>
    <string name="anmpp_wake_lock_set_false">关闭使设备保持在清醒状态</string>
    <string name="anmpp_boot_autostart_ngrokc_set_true">已经开启开机自动内网穿透</string>
    <string name="anmpp_boot_autostart_ngrokc_set_false">已经关闭开机自动内网穿透</string>
    <string name="anmpp_boot_autostart_ngrokc_done">执行内网穿透完毕</string>
    <string name="anmpp_bftpd_set">开启组件：BFTPD</string>
    <string name="anmpp_bftpd_set_true">已经开启组件：BFTPD</string>
    <string name="anmpp_bftpd_set_false">已经关闭组件：BFTPD</string>
    <string name="anmpp_nginx_set">开启组件：NGINX</string>
    <string name="anmpp_nginx_set_true">已经开启组件：NGINX</string>
    <string name="anmpp_nginx_set_false">已经关闭组件：NGINX</string>
    <string name="anmpp_mysql_set">开启组件：MYSQL</string>
    <string name="anmpp_mysql_set_true">已经开启组件：MYSQL</string>
    <string name="anmpp_mysql_set_false">已经关闭组件：MYSQL</string>
    <string name="anmpp_pgsql_set">开启组件：PGSQL</string>
    <string name="anmpp_pgsql_set_true">已经开启组件：PGSQL</string>
    <string name="anmpp_pgsql_set_false">已经关闭组件：PGSQL</string>
    <string name="anmpp_phpfpm_set">开启组件：PHP-FPM</string>
    <string name="anmpp_phpfpm_set_true">已经开启组件：PHP-FPM</string>
    <string name="anmpp_phpfpm_set_false">已经关闭组件：PHP-FPM</string>
    <string name="anmpp_run_set">运行管理</string>
    <string name="anmpp_plug_run_init">正在启动中....</string>
    <string name="anmpp_plug_run_stop">正在关闭中....</string>
    <string name="anmpp_plug_run_check">状态检查中....</string>
    <string name="anmpp_bftpd_run_title">服务管理：BFTPD</string>
    <string name="anmpp_bftpd_run_status_true">正在运行中....</string>
    <string name="anmpp_bftpd_run_status_false">点击这里启动服务</string>
    <string name="anmpp_nginx_run_title">服务管理：NGINX</string>
    <string name="anmpp_nginx_run_status_true">正在运行中....</string>
    <string name="anmpp_nginx_run_status_false">点击这里启动服务</string>
    <string name="anmpp_mysql_run_title">服务管理：MYSQL</string>
    <string name="anmpp_mysql_run_status_true">正在运行中....</string>
    <string name="anmpp_mysql_run_status_false">点击这里启动服务</string>
    <string name="anmpp_pgsql_run_title">服务管理：PGSQL</string>
    <string name="anmpp_pgsql_run_status_true">正在运行中....</string>
    <string name="anmpp_pgsql_run_status_false">点击这里启动服务</string>
    <string name="anmpp_phpfpm_run_title">服务管理：PHP-FPM</string>
    <string name="anmpp_phpfpm_run_status_true">正在运行中....</string>
    <string name="anmpp_phpfpm_run_status_false">点击这里启动服务</string>
    <string name="anmpp_plug_admin">组件管理</string>
    <string name="anmpp_base_admin">基本设置</string>
    <string name="anmpp_nattun_set">内网穿透</string>
    <string name="anmpp_ngrok_ngrokc_log_msg">点击这里查看穿透日志</string>
    <string name="anmpp_ngrok_ngrokc_log_title">内网穿透日志</string>
    <string name="anmpp_ngrok_ngrokc_log_load">日志加载中....</string>
    <string name="anmpp_ngrok_ngrokc_log_none">暂无日志供你查看</string>
    <string name="anmpp_ngrok_option_set_text">内网穿透选项</string>
    <string name="anmpp_ngrok_option_set_edit_title">设置内网穿透选项</string>
    <string name="anmpp_ngrok_option_set_edit_no">取消</string>
    <string name="anmpp_ngrok_option_set_edit_ok">保存</string>
    <string name="anmpp_ngrok_option_set_none">点此设置内网穿透相关选项</string>
    <string name="anmpp_ngrok_option_set_save_done">保存穿透选项成功</string>
    <string name="anmpp_ngrok_option_set_clear_done">清除穿透选项成功</string>
    <string name="anmpp_ngrok_option_set_check_fail">验证穿透选项失败</string>
    <string name="anmpp_ngrokc_admin">内网穿透管理</string>
    <string name="anmpp_ngrokc_run">正在运行中....</string>
    <string name="anmpp_ngrokc_stop">点此启动内网穿透</string>
    <string name="anmpp_ngrokc_status_check_dialog_msg">正在检查穿透状态....</string>
    <string name="anmpp_ngrokc_start_dialog_msg">正在启动内网穿透....</string>
    <string name="anmpp_ngrokc_stop_dialog_msg">正在停止内网穿透....</string>
    <string name="anmpp_stop_dialog_message">正在关闭你所开启的所有组件....</string>
    <string name="anmpp_start_dialog_message">正在启动你所开启的所有组件....</string>
    <string name="anmpp_reload_dialog_message">正在重启你所开启的所有组件....</string>
    <string name="anmpp_stop_dialog_done">执行停止操作完毕</string>
    <string name="anmpp_start_dialog_done">执行启动操作完毕</string>
    <string name="anmpp_reload_dialog_done">执行重启操作完毕</string>
    <string name="anmpp_install_dialog_title">从本机文件中安装集成环境？</string>
    <string name="anmpp_install_dialog_message">需要继续吗？将会使用系统最高权限执行一段程序来完成超级环境安装（安装结束时APP会自动关闭）！</string>
    <string name="anmpp_install_dialog_message_zip">选取的本地安装包路径：</string>
    <string name="anmpp_install_dialog_ok">确定安装</string>
    <string name="anmpp_install_dialog_no">稍后安装</string>
    <string name="anmpp_install_dialog_file_not_found">本机安装包文件不存在，请先准备好安装包文件！</string>
    <string name="anmpp_install_dialog_msg">集成环境正在安装中....</string>
    <string name="anmpp_install_done">超级集成环境已经成功安装</string>
    <string name="anmpp_uninstall_dialog_title">完全删除安装在本机的超级环境吗？</string>
    <string name="anmpp_uninstall_dialog_message">将会删除超级环境所有组件（包含WEB目录），卸载操作结束时APP会自动关闭，需要继续操作吗？</string>
    <string name="anmpp_uninstall_dialog_ok">彻底卸载</string>
    <string name="anmpp_uninstall_dialog_no">暂不卸载</string>
    <string name="anmpp_uninstall_dialog_msg">集成环境正在卸载中....</string>
    <string name="anmpp_uninstall_done">超级集成环境已经成功卸载</string>
    <string name="chooser_brw">请选择浏览器</string>
    <string name="open_localhost">已经为你执行打开本地主机地址</string>
    <string name="anmpp_version_title">版本信息</string>
    <string name="anmpp_binary_version_none">暂时无法识别你使用的版本</string>
</resources>
`

**Comment by xiaoqidun** [comment]
@0E800 [strings.zip](https://github.com/xiaoqidun/anmpp/files/849580/strings.zip)

**Comment by xiaoqidun** [comment]
@0E800 ，English translation already included in the latest apk。
